App\Entity\User:
  attributes:
    normalization_context:
      groups: [user_read]
  collectionOperations:
    register:
      method: POST
      path: /users/register
      controller: App\Controller\Action\User\Register
      denormalization_context:
        groups: [user_register]
      openapi_context:
        summary: Register a new user
  itemOperations:
    get:
      method: GET
