version: '3.5'

networks:
  udemyapiplatform-network:
    external: true

services:
  rabbit:
    container_name: ${DOCKER_NAME}-rabbitmq
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        UID: $U_ID
    volumes:
      - ./docker/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - udemyapiplatform-network
