App\Entity\UserAccountant:
  attributes:
    id:
      groups: [user_read]
    names:
      groups: [user_read, user_post]
    email:
      groups: [user_read, user_post]
    password:
      groups: [user_post]
    avatar:
      groups: [user_read]
    active:
      groups: [ user_read ]
    createdAt:
      groups: [ user_read ]
    updatedAt:
      groups: [ user_read ]
